### ISSUE TITLE
Pre-trained model for CVPR 2019

### ISSUE THREAD

**Issue by fedepare** [daniilidis-group/EV-FlowNet#12]
This is more of a question than an issue.

Is it possible to provide the pre-trained model of the optical flow network in your 2019 CVPR paper titled "Unsupervised Event-based Learning of Optical Flow, Depth, and Egomotion"?

Thanks in advance.

**Comment by fedepare** [comment]
Is there an update on this?

Thanks again in advance.

**Comment by alexzzhu** [comment]
Oops sorry this slid under my radar. It's a little tricky right now as my current employment is a little restrictive about me working on stuff outside of work. I think the best I can do is help if you wanted to do your own implementation.
